project_id = "isojguvcnfncokoxoauk"

[functions.logos-ai]
verify_jwt = true

[functions.corpus-ingest]
verify_jwt = true

[functions.bible-text]
verify_jwt = false

[functions.vatican-document]
verify_jwt = false
